name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "dist/*"
          target: "/var/www/thesis-survey-app-front/"
          rm: true
          overwrite: true
          if: github.event_name == 'push'
        
