name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Vue to Github Pages
        uses: xRealNeon/VuePagesAction@1.0.0
        with:
          username: ashkantaravati
          reponame: thesis-survey-app-front
          token: ${{ secrets.GITHUB_TOKEN }}
          cname: survey.ashkantaravati.ir
